name: http_miracle_mock
description: Designed for Flutter unit testing, this library allows for easy mocking/intercepting of network requests and images within business logic.
version: 0.0.3
homepage: https://github.com/xuzhongpeng/http_miracle_mock
repository: https://github.com/xuzhongpeng/http_miracle_mock
topics:
  - test
  - network
  - mock
  - intercept 
  - dio


environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  mockito: ^5.2.0
  path: ^1.8.1

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^4.0.6
  http: ^0.13.5
